mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.onepeice.fmmall.entity

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8&useSSL=false
    username: root
    type: com.alibaba.druid.pool.DruidDataSource